spring:
  application:
    name: springboot_rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
#    username: ems
    password: guest
#    password: 123
    virtual-host: /ems
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #none 自动确认  auto 根据情况确认  manual 手动确认
        retry:
          enabled: true #支持消息重试
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: false
    template:
      mandatory: true
    connection-timeout: 10000

# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /notax
